### ISSUE TITLE
Work on Presentation/Slide Deck

### ISSUE THREAD

**Issue by cdrathman11** [Ahmedalhenaki/creed#25]

**Comment by cdrathman11** [comment]
Meet up soon to do this. Here are the specs:
4 minutes long
8 slides
set slides to auto advance every 30 seconds
Default theme
Title slide will have our names
Overview of DFD - particularly the sections we expanded
Highlight 2 other documents
Provide experiences and difficulties
Provide takeaways from the project

**Comment by Ahmedalhenaki** [comment]
DONDE
